version: '3.8'

services:
  stay-hydrated:
    image: wandish/stay-hydrated:latest
    ports:
      - "8080:80"
    container_name: stay-hydrated-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stay-hydrated.rule=Host(`localhost`)"
      - "traefik.http.services.stay-hydrated.loadbalancer.server.port=80"

networks:
  default:
    name: stay-hydrated-network