services:
  stay-hydrated:
    image: wandish/stay-hydrated:latest
    container_name: stay-hydrated-app
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
