version: '3.8'

services:
  stay-hydrated:
    # Opción 1: Build local (desarrollo)
    build:
      context: .
      dockerfile: Dockerfile
    # Opción 2: Usar imagen de Docker Hub (producción)
    # image: wandish/stay-hydrated:latest
    ports:
      - "8080:80"
    container_name: stay-hydrated-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stay-hydrated.rule=Host(`localhost`)"
      - "traefik.http.services.stay-hydrated.loadbalancer.server.port=80"

  # Opcional: Servicio de desarrollo con hot reload
  stay-hydrated-dev:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./:/usr/share/nginx/html:ro
    container_name: stay-hydrated-dev
    restart: unless-stopped
    profiles:
      - dev

networks:
  default:
    name: stay-hydrated-network